"""Primera migracion

Revision ID: 868623bc9a0d
Revises: 
Create Date: 2025-01-04 17:34:41.060720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868623bc9a0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cursos', schema=None) as batch_op:
        batch_op.alter_column('Precio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cursos', schema=None) as batch_op:
        batch_op.alter_column('Precio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###
